apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/dciangot/kompose convert -f docker-compose.yml
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: cache
  name: cache
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cache
    spec:
      containers:
      - args:
        - --nogrid
        - --proxy
        - --health_port=8080
        env:
        - name: BLOCK_SIZE
          value: 512k
        - name: CACHE_LOG_LEVEL
          value: info
        - name: CACHE_PATH
          value: /data/xrd
        - name: CACHE_RAM_GB
          value: "12"
        - name: HI_WM
          value: "0.9"
        - name: LOW_WM
          value: "0.8"
        - name: N_PREFETCH
          value: "0"
        - name: ORIGIN_HOST
          value: origin
        - name: ORIGIN_XRD_PORT
          value: "1094"
        - name: REDIR_CMSD_PORT
          value: "1213"
        - name: REDIR_HOST
          value: redirector
        - name: STREAMS
          value: "256"
        image: cloudpg/xrootd-proxy:xrd
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080
        name: cache
        resources: {}
      restartPolicy: Always
status: {}
