kind: Pod
apiVersion: v1
metadata:
  name: xcache-pod
  labels:
    app: xcache
spec:

  nodeSelector:
    xcache-capable: "true"

  volumes:
  - name: xcache-data
    hostPath:
      path: /data/xrd

  containers:
  - name: cache
    args:
    - --nogrid
    - --proxy
    - --health_port
    - 8080
    env:
    - name: BLOCK_SIZE
      value: 512k
    - name: CACHE_LOG_LEVEL
      value: info
    - name: CACHE_PATH
      value: /data/xrd
    - name: CACHE_RAM_GB
      value: "12"
    - name: HI_WM
      value: "0.9"
    - name: LOW_WM
      value: "0.8"
    - name: N_PREFETCH
      value: "0"
    - name: ORIGIN_HOST
      value: origin
    - name: ORIGIN_XRD_PORT
      value: "1094"
    - name: REDIR_CMSD_PORT
      value: "1213"
    - name: REDIR_HOST
      value: redirector
    - name: STREAMS
      value: "256"
    image: cloudpg/xrootd-proxy:xrd
    livenessProbe:
      exec:
        command:
        - curl
        - -f
        - http://localhost:8080
    ports:
    - containerPort: 32294
    - containerPort: 31113

  - name: redirector
    args:
    - --nogrid
    - --redirector
    - --health_port
    - 8080
    env:
    - name: REDIR_CMSD_PORT
      value: "1213"
    - name: REDIR_HOST
      value: redirector
    - name: REDIR_XRD_PORT
      value: "1094"
    image: cloudpg/xrootd-proxy:xrd
    livenessProbe:
      exec:
        command:
        - curl
        - -f
        - http://localhost:8080
    ports:
    - containerPort: 1094
    - containerPort: 1213

    restartPolicy: Always
