version: '3'
services:
  cache:
    network_mode: "host"
    image: "cloudpg/xrootd-proxy"
    entrypoint:
      - python
      - /opt/xrd_proxy/entrypoint.py
      - --config 
      - /etc/xrootd/xrd_test.conf
      - --health_port
      - "8888"
      - --nogrid
  redirector:
    network_mode: "host"
    image: "cloudpg/xrootd-proxy"
    entrypoint:
      - python
      - /opt/xrd_proxy/entrypoint.py
      - --config 
      - /etc/xrootd/xrd_test_redir.conf  
      - --health_port
      - "8080"
      - --nogrid
  origin:
    network_mode: "host"
    image: "cloudpg/xrootd-proxy"
    entrypoint:
      - python
      - /opt/xrd_proxy/entrypoint.py
      - --config 
      - /etc/xrootd/xrd_test_origin.conf  
      - --health_port
      - "8081"
      - --nogrid

    
